/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FishingZonesRouteImport } from './routes/fishing-zones'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OceanConditionsRouteImport } from './routes/ocean-conditions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SavedLocationsRouteImport } from './routes/saved-locations'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FishingZonesRoute = FishingZonesRouteImport.update({
  id: '/fishing-zones',
  path: '/fishing-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanConditionsRoute = OceanConditionsRouteImport.update({
  id: '/ocean-conditions',
  path: '/ocean-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedLocationsRoute = SavedLocationsRouteImport.update({
  id: '/saved-locations',
  path: '/saved-locations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fishing-zones': typeof FishingZonesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/ocean-conditions': typeof OceanConditionsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/saved-locations': typeof SavedLocationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fishing-zones': typeof FishingZonesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/ocean-conditions': typeof OceanConditionsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/saved-locations': typeof SavedLocationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fishing-zones': typeof FishingZonesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/ocean-conditions': typeof OceanConditionsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/saved-locations': typeof SavedLocationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fishing-zones'
    | '/help'
    | '/history'
    | '/ocean-conditions'
    | '/profile'
    | '/safety'
    | '/saved-locations'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fishing-zones'
    | '/help'
    | '/history'
    | '/ocean-conditions'
    | '/profile'
    | '/safety'
    | '/saved-locations'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/fishing-zones'
    | '/help'
    | '/history'
    | '/ocean-conditions'
    | '/profile'
    | '/safety'
    | '/saved-locations'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FishingZonesRoute: typeof FishingZonesRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  OceanConditionsRoute: typeof OceanConditionsRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SavedLocationsRoute: typeof SavedLocationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing-zones': {
      id: '/fishing-zones'
      path: '/fishing-zones'
      fullPath: '/fishing-zones'
      preLoaderRoute: typeof FishingZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean-conditions': {
      id: '/ocean-conditions'
      path: '/ocean-conditions'
      fullPath: '/ocean-conditions'
      preLoaderRoute: typeof OceanConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-locations': {
      id: '/saved-locations'
      path: '/saved-locations'
      fullPath: '/saved-locations'
      preLoaderRoute: typeof SavedLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FishingZonesRoute: FishingZonesRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  OceanConditionsRoute: OceanConditionsRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SavedLocationsRoute: SavedLocationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
